# Generated by Django 4.0 on 2021-12-27 11:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FournisseurApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=0)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marque_modele', to='CarApp.marque')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeMoteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeVehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('couleur', models.CharField(default='', max_length=255)),
                ('puissance', models.IntegerField(default=0)),
                ('portes', models.IntegerField(default=0)),
                ('places', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('cylindres', models.IntegerField(default=0)),
                ('vitesse', models.IntegerField(default=0)),
                ('is_occasion', models.BooleanField(default=False)),
                ('image1', models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='stockage/images/pieces/')),
                ('image2', models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='stockage/images/pieces/')),
                ('image3', models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='stockage/images/pieces/')),
                ('image4', models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='stockage/images/pieces/')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutique_vehicule', to='FournisseurApp.boutique')),
                ('energie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energie_vehicule', to='CarApp.energie')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modele_vehicule', to='CarApp.modele')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmission_vehicule', to='CarApp.transmission')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_vehicule', to='CarApp.typevehicule')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
