# Generated by Django 4.0 on 2021-12-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FournisseurApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
